# vi: se ft=ansible:
#
# This role installs Caracas on a Raspberry Pi.

- include: default.yml
  tags:
    - default

- include: marble.yml
  tags:
    - marble

- include: raspberrypi.yml
  tags:
    - raspberrypi
